/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 *
 * @author Maiki
 */
public class Calculator extends javax.swing.JFrame {
    
    private float firstNumber;
    private float secondNumber;
    private String operator;

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                handleKeyPress(e);
            }
        });
        
        setFocusable(true); 
    }
    
    private void handleKeyPress(KeyEvent e) {
        char keyChar = e.getKeyChar();
        if (Character.isDigit(keyChar)) {
            screenOutput.setText(screenOutput.getText() + keyChar);
        } else {
            switch (keyChar) {
                case '+':
                    sumBtnActionPerformed(null);
                    break;
                case '-':
                    restBtnActionPerformed(null);
                    break;
                case '*':
                    jButton4ActionPerformed(null);
                    break;
                case '/':
                    divisionBtnActionPerformed(null);
                    break;
                case '=':
                case KeyEvent.VK_ENTER:
                    equalBtnActionPerformed(null);
                    break;
                case KeyEvent.VK_BACK_SPACE:
                    deleteOneNumberBtnActionPerformed(null);
                    break;
                case KeyEvent.VK_DELETE:
                    deleteBtnActionPerformed(null);
                    break;
                case '.':
                    pointBtnActionPerformed(null);
                    break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        screenOutput = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        divisionBtn = new javax.swing.JButton();
        restBtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        eightBtn = new javax.swing.JButton();
        nineBtn = new javax.swing.JButton();
        fiveBtn = new javax.swing.JButton();
        fourBtn = new javax.swing.JButton();
        sixBtn = new javax.swing.JButton();
        sumBtn = new javax.swing.JButton();
        threeBtn = new javax.swing.JButton();
        twoBtn = new javax.swing.JButton();
        sevenBtn = new javax.swing.JButton();
        zeroBtn = new javax.swing.JButton();
        pointBtn = new javax.swing.JButton();
        equalBtn = new javax.swing.JButton();
        oneBtn = new javax.swing.JButton();
        deleteOneNumberBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Basic Calculator");
        setName("CalculatorFrame"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        screenOutput.setBackground(new java.awt.Color(255, 255, 255));
        screenOutput.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        screenOutput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        screenOutput.setOpaque(true);

        deleteBtn.setBackground(new java.awt.Color(211, 47, 47));
        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("C");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        divisionBtn.setBackground(new java.awt.Color(153, 153, 153));
        divisionBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        divisionBtn.setForeground(new java.awt.Color(255, 255, 255));
        divisionBtn.setText("/");
        divisionBtn.setBorder(null);
        divisionBtn.setBorderPainted(false);
        divisionBtn.setFocusPainted(false);
        divisionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionBtnActionPerformed(evt);
            }
        });

        restBtn.setBackground(new java.awt.Color(153, 153, 153));
        restBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        restBtn.setForeground(new java.awt.Color(255, 255, 255));
        restBtn.setText("-");
        restBtn.setBorder(null);
        restBtn.setBorderPainted(false);
        restBtn.setFocusPainted(false);
        restBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restBtnActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("*");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        eightBtn.setBackground(new java.awt.Color(153, 153, 153));
        eightBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        eightBtn.setForeground(new java.awt.Color(255, 255, 255));
        eightBtn.setText("8");
        eightBtn.setBorder(null);
        eightBtn.setBorderPainted(false);
        eightBtn.setFocusPainted(false);
        eightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightBtnActionPerformed(evt);
            }
        });

        nineBtn.setBackground(new java.awt.Color(153, 153, 153));
        nineBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        nineBtn.setForeground(new java.awt.Color(255, 255, 255));
        nineBtn.setText("9");
        nineBtn.setBorder(null);
        nineBtn.setBorderPainted(false);
        nineBtn.setFocusPainted(false);
        nineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineBtnActionPerformed(evt);
            }
        });

        fiveBtn.setBackground(new java.awt.Color(153, 153, 153));
        fiveBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        fiveBtn.setForeground(new java.awt.Color(255, 255, 255));
        fiveBtn.setText("5");
        fiveBtn.setBorder(null);
        fiveBtn.setBorderPainted(false);
        fiveBtn.setFocusPainted(false);
        fiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveBtnActionPerformed(evt);
            }
        });

        fourBtn.setBackground(new java.awt.Color(153, 153, 153));
        fourBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        fourBtn.setForeground(new java.awt.Color(255, 255, 255));
        fourBtn.setText("4");
        fourBtn.setBorder(null);
        fourBtn.setBorderPainted(false);
        fourBtn.setFocusPainted(false);
        fourBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourBtnActionPerformed(evt);
            }
        });

        sixBtn.setBackground(new java.awt.Color(153, 153, 153));
        sixBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        sixBtn.setForeground(new java.awt.Color(255, 255, 255));
        sixBtn.setText("6");
        sixBtn.setBorder(null);
        sixBtn.setBorderPainted(false);
        sixBtn.setFocusPainted(false);
        sixBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixBtnActionPerformed(evt);
            }
        });

        sumBtn.setBackground(new java.awt.Color(153, 153, 153));
        sumBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        sumBtn.setForeground(new java.awt.Color(255, 255, 255));
        sumBtn.setText("+");
        sumBtn.setBorder(null);
        sumBtn.setBorderPainted(false);
        sumBtn.setFocusPainted(false);
        sumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumBtnActionPerformed(evt);
            }
        });

        threeBtn.setBackground(new java.awt.Color(153, 153, 153));
        threeBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        threeBtn.setForeground(new java.awt.Color(255, 255, 255));
        threeBtn.setText("3");
        threeBtn.setBorder(null);
        threeBtn.setBorderPainted(false);
        threeBtn.setFocusPainted(false);
        threeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeBtnActionPerformed(evt);
            }
        });

        twoBtn.setBackground(new java.awt.Color(153, 153, 153));
        twoBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        twoBtn.setForeground(new java.awt.Color(255, 255, 255));
        twoBtn.setText("2");
        twoBtn.setBorder(null);
        twoBtn.setBorderPainted(false);
        twoBtn.setFocusPainted(false);
        twoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoBtnActionPerformed(evt);
            }
        });

        sevenBtn.setBackground(new java.awt.Color(153, 153, 153));
        sevenBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        sevenBtn.setForeground(new java.awt.Color(255, 255, 255));
        sevenBtn.setText("7");
        sevenBtn.setBorder(null);
        sevenBtn.setBorderPainted(false);
        sevenBtn.setFocusPainted(false);
        sevenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenBtnActionPerformed(evt);
            }
        });

        zeroBtn.setBackground(new java.awt.Color(153, 153, 153));
        zeroBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        zeroBtn.setForeground(new java.awt.Color(255, 255, 255));
        zeroBtn.setText("0");
        zeroBtn.setBorderPainted(false);
        zeroBtn.setFocusPainted(false);
        zeroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroBtnActionPerformed(evt);
            }
        });

        pointBtn.setBackground(new java.awt.Color(153, 153, 153));
        pointBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        pointBtn.setForeground(new java.awt.Color(255, 255, 255));
        pointBtn.setText(".");
        pointBtn.setBorderPainted(false);
        pointBtn.setFocusPainted(false);
        pointBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointBtnActionPerformed(evt);
            }
        });

        equalBtn.setBackground(new java.awt.Color(79, 195, 247));
        equalBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        equalBtn.setForeground(new java.awt.Color(255, 255, 255));
        equalBtn.setText("=");
        equalBtn.setBorderPainted(false);
        equalBtn.setFocusPainted(false);
        equalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalBtnActionPerformed(evt);
            }
        });

        oneBtn.setBackground(new java.awt.Color(153, 153, 153));
        oneBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        oneBtn.setForeground(new java.awt.Color(255, 255, 255));
        oneBtn.setText("1");
        oneBtn.setBorder(null);
        oneBtn.setBorderPainted(false);
        oneBtn.setFocusPainted(false);
        oneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneBtnActionPerformed(evt);
            }
        });

        deleteOneNumberBtn.setBackground(new java.awt.Color(153, 153, 153));
        deleteOneNumberBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        deleteOneNumberBtn.setForeground(new java.awt.Color(255, 0, 51));
        deleteOneNumberBtn.setText("Del");
        deleteOneNumberBtn.setBorder(null);
        deleteOneNumberBtn.setBorderPainted(false);
        deleteOneNumberBtn.setFocusPainted(false);
        deleteOneNumberBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteOneNumberBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(screenOutput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(divisionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteOneNumberBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(zeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(pointBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(sevenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(eightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(oneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(twoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(fourBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fiveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sixBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(threeBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(equalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sumBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(restBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(screenOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteOneNumberBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divisionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sevenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sixBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fiveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fourBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sumBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(threeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(twoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pointBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(equalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
       this.screenOutput.setText("");
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void divisionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionBtnActionPerformed

        try{
        
            firstNumber = Float.parseFloat(screenOutput.getText());
        
            operator = "/";
        
            screenOutput.setText("");
        
        }catch(Exception ex){
            System.out.println("No se introdujo ningun numero");
        }
    }//GEN-LAST:event_divisionBtnActionPerformed

    private void restBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restBtnActionPerformed
        
        try{
        
            firstNumber = Float.parseFloat(screenOutput.getText());
        
            operator = "-";
        
            screenOutput.setText("");
        
        }catch(Exception ex){
            System.out.println("No se introdujo ningun numero");
        }
    }//GEN-LAST:event_restBtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        try{

            firstNumber = Float.parseFloat(screenOutput.getText());
        
            operator = "*";
        
            screenOutput.setText("");
        
        }catch(Exception ex){
            System.out.println("No se introdujo ningun numero");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void eightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightBtnActionPerformed
       this.screenOutput.setText(this.screenOutput.getText() + "8");
    }//GEN-LAST:event_eightBtnActionPerformed

    private void nineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineBtnActionPerformed
       this.screenOutput.setText(this.screenOutput.getText() + "9");
    }//GEN-LAST:event_nineBtnActionPerformed

    private void fiveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveBtnActionPerformed
       this.screenOutput.setText(this.screenOutput.getText() + "5");
    }//GEN-LAST:event_fiveBtnActionPerformed

    private void fourBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourBtnActionPerformed
       this.screenOutput.setText(this.screenOutput.getText() + "4");
    }//GEN-LAST:event_fourBtnActionPerformed

    private void sixBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixBtnActionPerformed
        this.screenOutput.setText(this.screenOutput.getText() + "6");
    }//GEN-LAST:event_sixBtnActionPerformed

    private void sumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumBtnActionPerformed
    
        try{
            
            firstNumber = Float.parseFloat(screenOutput.getText());
        
            operator = "+";
        
            screenOutput.setText("");
        
        }catch(Exception ex){
            System.out.println("No se introdujo ningun numero");
        }
        
    }//GEN-LAST:event_sumBtnActionPerformed

    private void threeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeBtnActionPerformed
        this.screenOutput.setText(this.screenOutput.getText() + "3");
    }//GEN-LAST:event_threeBtnActionPerformed

    private void twoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoBtnActionPerformed
        this.screenOutput.setText(this.screenOutput.getText() + "2");
    }//GEN-LAST:event_twoBtnActionPerformed

    private void sevenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenBtnActionPerformed
      this.screenOutput.setText(this.screenOutput.getText() + "7");
    }//GEN-LAST:event_sevenBtnActionPerformed

    private void zeroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroBtnActionPerformed
        this.screenOutput.setText(this.screenOutput.getText() + "0");
    }//GEN-LAST:event_zeroBtnActionPerformed

    private void pointBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointBtnActionPerformed
        if(!screenOutput.getText().contains(".")){
            screenOutput.setText(screenOutput.getText() + ".");
        }
    }//GEN-LAST:event_pointBtnActionPerformed

    private void equalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalBtnActionPerformed
        
       try{
           
        secondNumber = Float.parseFloat(screenOutput.getText());
        
        switch(operator){
            
            case "+": screenOutput.setText(withoutZero(firstNumber + secondNumber));
            break;
            case "-": screenOutput.setText(withoutZero(firstNumber - secondNumber));
            break;
            case "*": screenOutput.setText(withoutZero(firstNumber * secondNumber));
            break;
            case "/":
                if(secondNumber == 0){
                    screenOutput.setText("Sintax Error" + ": " + "division by zero is undefined");
                
                }else{
                    screenOutput.setText(withoutZero(firstNumber / secondNumber));
                }
        }
        
       }catch(Exception ex){
           System.out.println("No se introdujo ningun numero o el segundo numero esta vacio");
       }
        
    }//GEN-LAST:event_equalBtnActionPerformed

    private void oneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneBtnActionPerformed
       screenOutput.setText(screenOutput.getText() + "1");
    }//GEN-LAST:event_oneBtnActionPerformed

    private void deleteOneNumberBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteOneNumberBtnActionPerformed

        try{

            delete();

        }catch(Exception ex){
            System.out.println("No se introdujo ningun numero");
        }
    }//GEN-LAST:event_deleteOneNumberBtnActionPerformed

    
    public String withoutZero(float result){
        
        String resultString = "";
        
        resultString =Float.toString(result);
        
        if(result%1 == 0){
        
           resultString = resultString.substring(0,resultString.length()-2);
        }
        
        return resultString;
        
    }
    
    public void delete(){
        
        String result = "";
        
        result = screenOutput.getText();
         
        result = result.substring(0,result.length()-1);
         
        screenOutput.setText(result);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

         
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton deleteOneNumberBtn;
    private javax.swing.JButton divisionBtn;
    private javax.swing.JButton eightBtn;
    private javax.swing.JButton equalBtn;
    private javax.swing.JButton fiveBtn;
    private javax.swing.JButton fourBtn;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nineBtn;
    private javax.swing.JButton oneBtn;
    private javax.swing.JButton pointBtn;
    private javax.swing.JButton restBtn;
    private javax.swing.JLabel screenOutput;
    private javax.swing.JButton sevenBtn;
    private javax.swing.JButton sixBtn;
    private javax.swing.JButton sumBtn;
    private javax.swing.JButton threeBtn;
    private javax.swing.JButton twoBtn;
    private javax.swing.JButton zeroBtn;
    // End of variables declaration//GEN-END:variables
}
